### ISSUE TITLE
Stack folder naming

### ISSUE THREAD

**Issue by mquadrant** [adedayojs/vue-boilerplate#1]
I do believe it is conventional to just Server and Client instead of Backend and Frontend respectively. If you agree to this change, you could let me know, I am creating a PR with some few changes.

**Comment by adedayojs** [comment]
Thanks. I also used server and client before, but I thought it might confuse some newbies, hence the renamng. Thanks though

**Comment by mquadrant** [comment]
I think it is more conventional to have server/client

**Comment by adedayojs** [comment]
Thanks bro
